// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('crowdFundApp')
    .config(function($logProvider, $authProvider, $stateProvider, $locationProvider, CONFIG, $urlRouterProvider) {
      'ngInject';
      $logProvider.debugEnabled(true);
      $authProvider.configure([{
        default: {
          apiUrl: CONFIG.apiUrl
        }
      }, {
        admin: {
          apiUrl: CONFIG.apiUrl,
          signOutUrl: '/admin_auth/sign_out',
          emailSignInPath: '/admin_auth/sign_in',
          passwordResetPath: '/admin_auth/password',
          passwordUpdatePath: '/admin_auth/password',
          tokenValidationPath: '/admin_auth/validate_token'
        }
      }]);
    })
}).call(this);
