// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('alMakinah').config(function($stateProvider, $urlRouterProvider, $locationProvider) {
    'ngInject';
    $locationProvider.html5Mode(true);
    $stateProvider.state("dashboard", {
      abstract: true,
      templateUrl: "app/views/layouts/dashboard_layout.html",
      controller: "DashboardController"
    }).state("dashboard.home", {
      url: "/",
      templateUrl: "app/views/dashboard/index.html"
    }).state({
      name: 'landing',
      url: '/',
      templateUrl: 'app/views/landing/landing.html'
    }).state({
      name: 'sign_in',
      url: '/sign_in',
      templateUrl: 'app/views/sessions/session_sign_in.html'
    }).state({
      name: 'sign_up',
      url: '/sign_up',
      templateUrl: 'app/views/sessions/session_sign_up.html'
    }).state({
      name: 'admin_sign_in',
      url: '/admins/sign_in',
      templateUrl: 'app/views/sessions/session_admin_sign_in.html'
    }).state({
      name: 'campaigns',
      url: '/campaigns',
      templateUrl: 'app/views/campaigns/campaign.index.html',
      // resolve: {
      //   auth: function ($auth) {
      //     return $auth.validateUser();
      //   }},
      controller: 'campaignsIndex'
    }).state({
      name: 'campaigns_create',
      url: '/campaigns/new',
      templateUrl: 'app/views/campaigns/campaign.new.html',
      controller: 'campaignNew',
      resolve: {
        auth: function($auth) {
          return $auth.validateUser();
        }
      },
    }).state({
      name: 'campaign_show',
      url: '/campaigns/:id',
      templateUrl: 'app/views/campaigns/campaign.show.html',
      controller: 'campaignShow'
    }).state({
      name: 'admin_campaign',
      url: '/admins/campaigns',
      templateUrl: 'app/views/admin/admin.campaign.html',
      controller: 'adminCampaignCtrl'
    });

    return $urlRouterProvider.otherwise('/');
  });

}).call(this);
