// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('alMakinah').config(function($authProvider, $logProvider) {
    'ngInject';
    $logProvider.debugEnabled(true);

    $authProvider.configure([{
      default: {
        apiUrl: "http://localhost:3000"
      }
    }, {

      admin: {
        apiUrl: "http://localhost:3000",
        signOutUrl: '/admin_auth/sign_out',
        emailSignInPath: '/admin_auth/sign_in',
        passwordResetPath: '/admin_auth/password',
        passwordUpdatePath: '/admin_auth/password',
        tokenValidationPath: '/admin_auth/validate_token'
      }
    }])
  });

}).call(this);
