// Generated by CoffeeScript 1.10.0
(function() {
  angular.
    module('crowdFundApp', [
        'ngAnimate',
        'ngCookies',
        'ngSanitize',
        'ngStorage',
        'ui.router',
        'ui.bootstrap',
        'toaster',
        'ng-token-auth',
        'ipCookie',
        'ui.router',
        'yaru22.angular-timeago',
        'angularPayments',
        'ngFileUpload'
    ]);

}).call(this);
