// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('crowdFundApp').config(function($stateProvider, $urlRouterProvider, $locationProvider) {
    'ngInject';
    $locationProvider.html5Mode(true);
    $stateProvider.state({
      name: 'dashboard_layout',
      templateUrl: 'app/views/layouts/dashboard_layout.html',
      abstract:true
    }).state({
      name: 'dashboard_layout.landing',
      url: '/',
      templateUrl: 'app/views/landing/landing.html'
    }).state({
      name: 'sign_in',
      url: '/sign_in',
      templateUrl: 'app/views/sessions/session_sign_in.html'
    }).state({
      name: 'sign_up',
      url: '/sign_up',
      templateUrl: 'app/views/sessions/session_sign_up.html'
    }).state({
      name: 'admin_sign_in',
      url: '/admins/sign_in',
      templateUrl: 'app/views/sessions/session_admin_sign_in.html'
    }).state({
      name: 'campaigns',
      url: '/campaigns',
      templateUrl: 'app/views/campaigns/campaign.index.html',
      controller: 'campaignsIndex'
    }).state({
      name: 'campaigns_create',
      url: '/campaigns/new',
      templateUrl: 'app/views/campaigns/campaign.new.html',
      controller: 'campaignNew',
      resolve: {
        resolvedUser: function($auth, $state, validationService) {
          validationService.authenticateDefault($auth, $state)
        }
      },
    }).state({
      name: 'campaign_show',
      url: '/campaigns/:id',
      templateUrl: 'app/views/campaigns/campaign.show.html',
      controller: 'campaignShow'
    }).state({
      name: 'admin_campaign',
      url: '/admins/campaigns',
      templateUrl: 'app/views/admin/admin.campaign.html',
      controller: 'adminCampaignCtrl',
      resolve: {
        resolvedUser: function($auth, $state, validationService) {
          validationService.authenticateAdmin($auth, $state)
        },
      },
    }).state({
      name: 'user_profile_show',
      url: '/users/:id',
      templateUrl: 'app/views/users/user_profile.html',
      controller: 'userShow'
    }).state({
      name: 'user_profile_edit',
      url: '/users/edit/:id',
      templateUrl: 'app/views/users/edit_profile.html',
      controller: 'userEdit'
    }).state({
      name: 'payment_form',
      url: '/campaigns/:id/payment',
      templateUrl: 'app/views/payment/payment.html',
      controller: 'payment',
      resolve: {
        resolvedUser: function($auth, $state, validationService) {
          validationService.authenticateDefault($auth, $state)
        }
      },
    });

    $urlRouterProvider.otherwise('/');
  });

}).call(this);
